import type { Recommendation } from "@/types";

const now = Date.now();

const seededRecommendations: Omit<Recommendation, "dataSource">[] = [
  {
    id: "r-001",
    rank: 1,
    title: "Helios Solar Roll-up (Spain/Portugal)",
    region: "Europe",
    sector: "Solar & Energy",
    country: "ES",
    capitalUsd: 320_000_000,
    irrPct: 16.8,
    horizonYears: 8,
    riskLevel: "medium",
    confidence: 94,
    status: "approved",
    tags: ["ESG-Aligned", "Infrastructure", "Long-Term"],
    rationale:
      "Portfolio of contracted PV assets with inflation-linked PPAs; downside protected through conservative leverage and stable O&M cost curve.",
    scoreBreakdown: [
      { dimension: "Market Size", score: 78 },
      { dimension: "ESG", score: 92 },
      { dimension: "IRR", score: 86 },
      { dimension: "Risk", score: 62 },
      { dimension: "Portfolio Fit", score: 80 },
      { dimension: "Liquidity", score: 58 },
    ],
    modelVersion: "dl-3.2",
    generatedAt: new Date(now - 1000 * 60 * 12).toISOString(),
    riskFactors: ["Regulatory", "Market", "Liquidity"],
  },
  {
    id: "r-002",
    rank: 2,
    title: "Bluewater Utility-Scale Solar (Texas)",
    region: "North America",
    sector: "Solar & Energy",
    country: "US",
    capitalUsd: 210_000_000,
    irrPct: 15.1,
    horizonYears: 7,
    riskLevel: "low",
    confidence: 90,
    status: "approved",
    tags: ["ESG-Aligned", "Defensive"],
    rationale:
      "Interconnection secured and merchant exposure capped via collars; construction EPC fixed-price with reputable counterparty.",
    scoreBreakdown: [
      { dimension: "Market Size", score: 74 },
      { dimension: "ESG", score: 89 },
      { dimension: "IRR", score: 79 },
      { dimension: "Risk", score: 71 },
      { dimension: "Portfolio Fit", score: 77 },
      { dimension: "Liquidity", score: 61 },
    ],
    modelVersion: "dl-3.2",
    generatedAt: new Date(now - 1000 * 60 * 28).toISOString(),
    riskFactors: ["Operational", "Market"],
  },
  {
    id: "r-003",
    rank: 3,
    title: "Sunrise Distributed Solar Finance (India)",
    region: "APAC",
    sector: "Solar & Energy",
    country: "IN",
    capitalUsd: 140_000_000,
    irrPct: 18.9,
    horizonYears: 6,
    riskLevel: "high",
    confidence: 76,
    status: "pending_review",
    tags: ["High-Growth", "ESG-Aligned"],
    rationale:
      "High demand from C&I rooftops with attractive yields; underwriting requires tighter defaults stress due to SME credit dispersion.",
    scoreBreakdown: [
      { dimension: "Market Size", score: 82 },
      { dimension: "ESG", score: 90 },
      { dimension: "IRR", score: 91 },
      { dimension: "Risk", score: 49 },
      { dimension: "Portfolio Fit", score: 70 },
      { dimension: "Liquidity", score: 44 },
    ],
    modelVersion: "dl-3.2",
    generatedAt: new Date(now - 1000 * 60 * 55).toISOString(),
    riskFactors: ["Credit", "Geopolitical", "Regulatory"],
  },
  {
    id: "r-004",
    rank: 4,
    title: "Gulfstream Midstream (Permian) — Expansion Capex",
    region: "North America",
    sector: "Oil & Gas",
    country: "US",
    capitalUsd: 260_000_000,
    irrPct: 14.2,
    horizonYears: 5,
    riskLevel: "high",
    confidence: 72,
    status: "rejected",
    tags: ["Commodity-Linked", "High-IRR"],
    rationale:
      "Volume commitments are credible but commodity beta dominates; the bear and stress macro cases breach portfolio volatility tolerance.",
    scoreBreakdown: [
      { dimension: "Market Size", score: 68 },
      { dimension: "ESG", score: 41 },
      { dimension: "IRR", score: 84 },
      { dimension: "Risk", score: 38 },
      { dimension: "Portfolio Fit", score: 52 },
      { dimension: "Liquidity", score: 60 },
    ],
    modelVersion: "dl-3.2",
    generatedAt: new Date(now - 1000 * 60 * 85).toISOString(),
    riskFactors: ["Market", "ESG / Reputation", "Regulatory"],
  },
  {
    id: "r-005",
    rank: 5,
    title: "North Sea Decommissioning Services Platform",
    region: "Europe",
    sector: "Oil & Gas",
    country: "GB",
    capitalUsd: 175_000_000,
    irrPct: 17.6,
    horizonYears: 4,
    riskLevel: "medium",
    confidence: 83,
    status: "under_review",
    tags: ["Defensive", "Infrastructure"],
    rationale:
      "Late-life asset activity is resilient; diligence centers on contract margin floors and HSE incident history.",
    scoreBreakdown: [
      { dimension: "Market Size", score: 61 },
      { dimension: "ESG", score: 55 },
      { dimension: "IRR", score: 88 },
      { dimension: "Risk", score: 64 },
      { dimension: "Portfolio Fit", score: 73 },
      { dimension: "Liquidity", score: 57 },
    ],
    modelVersion: "dl-3.2",
    generatedAt: new Date(now - 1000 * 60 * 120).toISOString(),
    riskFactors: ["Operational", "Regulatory"],
  },
  {
    id: "r-006",
    rank: 6,
    title: "Neobank Expansion — SME Lending (Brazil)",
    region: "Latin America",
    sector: "Banking",
    country: "BR",
    capitalUsd: 90_000_000,
    irrPct: 22.1,
    horizonYears: 5,
    riskLevel: "high",
    confidence: 62,
    status: "pending_review",
    tags: ["Fintech", "High-Growth", "High-IRR"],
    rationale:
      "Unit economics are attractive, but credit losses in stress macro case are uncertain; require tighter underwriting and FX hedging plan.",
    scoreBreakdown: [
      { dimension: "Market Size", score: 79 },
      { dimension: "ESG", score: 63 },
      { dimension: "IRR", score: 95 },
      { dimension: "Risk", score: 35 },
      { dimension: "Portfolio Fit", score: 58 },
      { dimension: "Liquidity", score: 46 },
    ],
    modelVersion: "dl-3.2",
    generatedAt: new Date(now - 1000 * 60 * 150).toISOString(),
    riskFactors: ["Credit", "Liquidity", "Geopolitical"],
  },
  {
    id: "r-007",
    rank: 7,
    title: "Regional Bank M&A Arbitrage Basket (US)",
    region: "North America",
    sector: "Banking",
    country: "US",
    capitalUsd: 130_000_000,
    irrPct: 13.4,
    horizonYears: 3,
    riskLevel: "medium",
    confidence: 78,
    status: "approved",
    tags: ["Defensive"],
    rationale:
      "Spread capture strategy with tight risk budget; benefits from rate normalization but sensitive to regulatory approvals.",
    scoreBreakdown: [
      { dimension: "Market Size", score: 66 },
      { dimension: "ESG", score: 70 },
      { dimension: "IRR", score: 72 },
      { dimension: "Risk", score: 61 },
      { dimension: "Portfolio Fit", score: 74 },
      { dimension: "Liquidity", score: 73 },
    ],
    modelVersion: "dl-3.2",
    generatedAt: new Date(now - 1000 * 60 * 175).toISOString(),
    riskFactors: ["Regulatory", "Market"],
  },
  {
    id: "r-008",
    rank: 8,
    title: "Tier-2 Bank Capital Relief Notes (EU)",
    region: "Europe",
    sector: "Banking",
    country: "DE",
    capitalUsd: 110_000_000,
    irrPct: 12.2,
    horizonYears: 4,
    riskLevel: "low",
    confidence: 88,
    status: "approved",
    tags: ["Defensive", "Long-Term"],
    rationale:
      "Capital stack positioning offers convexity with strong issuer buffers; monitor policy changes impacting risk weights.",
    scoreBreakdown: [
      { dimension: "Market Size", score: 60 },
      { dimension: "ESG", score: 73 },
      { dimension: "IRR", score: 69 },
      { dimension: "Risk", score: 74 },
      { dimension: "Portfolio Fit", score: 76 },
      { dimension: "Liquidity", score: 80 },
    ],
    modelVersion: "dl-3.2",
    generatedAt: new Date(now - 1000 * 60 * 210).toISOString(),
    riskFactors: ["Credit", "Regulatory"],
  },
  {
    id: "r-009",
    rank: 9,
    title: "Hospital Network Expansion (France) — Brownfield",
    region: "Europe",
    sector: "Hospitals",
    country: "FR",
    capitalUsd: 240_000_000,
    irrPct: 10.7,
    horizonYears: 9,
    riskLevel: "low",
    confidence: 92,
    status: "pending_review",
    tags: ["Defensive", "Infrastructure"],
    rationale:
      "Stable reimbursement framework and high occupancy; diligence focuses on capex backlog and labor availability.",
    scoreBreakdown: [
      { dimension: "Market Size", score: 64 },
      { dimension: "ESG", score: 78 },
      { dimension: "IRR", score: 60 },
      { dimension: "Risk", score: 76 },
      { dimension: "Portfolio Fit", score: 82 },
      { dimension: "Liquidity", score: 55 },
    ],
    modelVersion: "dl-3.2",
    generatedAt: new Date(now - 1000 * 60 * 245).toISOString(),
    riskFactors: ["Operational", "Regulatory"],
  },
  {
    id: "r-010",
    rank: 10,
    title: "US Outpatient Clinics Roll-up — Value-Based Care",
    region: "North America",
    sector: "Hospitals",
    country: "US",
    capitalUsd: 150_000_000,
    irrPct: 19.3,
    horizonYears: 6,
    riskLevel: "medium",
    confidence: 74,
    status: "under_review",
    tags: ["High-Growth", "High-IRR"],
    rationale:
      "Growth supported by payer shift and M&A pipeline; execution risk centers on integration and clinician retention.",
    scoreBreakdown: [
      { dimension: "Market Size", score: 81 },
      { dimension: "ESG", score: 77 },
      { dimension: "IRR", score: 90 },
      { dimension: "Risk", score: 58 },
      { dimension: "Portfolio Fit", score: 69 },
      { dimension: "Liquidity", score: 52 },
    ],
    modelVersion: "dl-3.2",
    generatedAt: new Date(now - 1000 * 60 * 275).toISOString(),
    riskFactors: ["Operational", "Credit"],
  },
  {
    id: "r-011",
    rank: 11,
    title: "Water Utility Rehabilitation (Chile) — PPP",
    region: "Latin America",
    sector: "Water Treatment",
    country: "CL",
    capitalUsd: 190_000_000,
    irrPct: 12.9,
    horizonYears: 10,
    riskLevel: "medium",
    confidence: 80,
    status: "approved",
    tags: ["Infrastructure", "ESG-Aligned", "Long-Term"],
    rationale:
      "Tariff framework supports upgrades; key monitoring items are FX pass-through and regulatory cadence.",
    scoreBreakdown: [
      { dimension: "Market Size", score: 55 },
      { dimension: "ESG", score: 88 },
      { dimension: "IRR", score: 71 },
      { dimension: "Risk", score: 59 },
      { dimension: "Portfolio Fit", score: 78 },
      { dimension: "Liquidity", score: 47 },
    ],
    modelVersion: "dl-3.2",
    generatedAt: new Date(now - 1000 * 60 * 315).toISOString(),
    riskFactors: ["Regulatory", "Geopolitical"],
  },
  {
    id: "r-012",
    rank: 12,
    title: "Regenerative Agriculture Inputs Platform (Kenya)",
    region: "Africa",
    sector: "Agriculture",
    country: "KE",
    capitalUsd: 60_000_000,
    irrPct: 21.4,
    horizonYears: 5,
    riskLevel: "high",
    confidence: 69,
    status: "rejected",
    tags: ["ESG-Aligned", "High-Growth"],
    rationale:
      "Strong impact case; commercial scaling and FX uncertainty reduce investability until customer churn stabilizes.",
    scoreBreakdown: [
      { dimension: "Market Size", score: 77 },
      { dimension: "ESG", score: 94 },
      { dimension: "IRR", score: 87 },
      { dimension: "Risk", score: 33 },
      { dimension: "Portfolio Fit", score: 45 },
      { dimension: "Liquidity", score: 29 },
    ],
    modelVersion: "dl-3.2",
    generatedAt: new Date(now - 1000 * 60 * 355).toISOString(),
    riskFactors: ["Geopolitical", "Market", "Liquidity"],
  },
];

// Seeded fixtures are all mock provenance; AI-generated recs are tagged "live" at write time.
export const recommendations: Recommendation[] = seededRecommendations.map((rec) => ({
  ...rec,
  dataSource: "mock",
}));
