import type { RiskFactorScore } from "@/types";

export const riskScores: RiskFactorScore[] = [
  {
    id: "rf-market",
    name: "Market",
    score: 68,
    previousScore: 64,
    sparklineData: [61, 62, 60, 63, 64, 66, 68],
    source: "bloomberg",
    region: "Global",
  },
  {
    id: "rf-credit",
    name: "Credit",
    score: 57,
    previousScore: 59,
    sparklineData: [62, 61, 60, 59, 58, 58, 57],
    source: "bloomberg",
    region: "Global",
  },
  {
    id: "rf-liquidity",
    name: "Liquidity",
    score: 63,
    previousScore: 60,
    sparklineData: [58, 59, 60, 60, 61, 62, 63],
    source: "manual",
    region: "Global",
  },
  {
    id: "rf-operational",
    name: "Operational",
    score: 52,
    previousScore: 51,
    sparklineData: [50, 50, 51, 51, 52, 52, 52],
    source: "manual",
    region: "Global",
  },
  {
    id: "rf-regulatory",
    name: "Regulatory",
    score: 70,
    previousScore: 66,
    sparklineData: [63, 64, 64, 65, 66, 68, 70],
    source: "talkwalker",
    region: "Europe",
  },
  {
    id: "rf-esg",
    name: "ESG / Reputation",
    score: 61,
    previousScore: 58,
    sparklineData: [55, 56, 57, 58, 58, 60, 61],
    source: "talkwalker",
    region: "Global",
  },
  {
    id: "rf-geopolitical",
    name: "Geopolitical",
    score: 66,
    previousScore: 67,
    sparklineData: [65, 66, 67, 68, 67, 66, 66],
    source: "bloomberg",
    region: "Global",
  },
];
