import type { Signal } from "@/types";

const now = Date.now();

function isoMinutesAgo(min: number) {
  return new Date(now - min * 60_000).toISOString();
}

export const seededSignals: Signal[] = [
  // critical ×2
  {
    id: "s-001",
    title: "Regulator flags capital buffer review for EU banks",
    body: "Preliminary consultation suggests higher risk weights for certain SME exposures; monitor impact to Banking sleeve.",
    type: "policy",
    severity: "critical",
    sentiment: -0.55,
    reach: 0,
    timestamp: isoMinutesAgo(18),
    source: "bloomberg",
    country: "DE",
    region: "Europe",
    sector: "Banking",
    riskFactor: "Regulatory",
  },
  {
    id: "s-002",
    title: "Supply chain controversy: labor audit escalation for Materials issuer",
    body: "Third-party audit indicates elevated compliance risk; ESG review required for Materials allocations.",
    type: "risk",
    severity: "critical",
    sentiment: -0.72,
    reach: 420_000,
    timestamp: isoMinutesAgo(42),
    source: "talkwalker",
    country: "CL",
    region: "Latin America",
    sector: "Hotels",
    riskFactor: "ESG / Reputation",
  },

  // high ×5
  {
    id: "s-003",
    title: "Oil volatility spikes on inventory draw; hedging costs rise",
    body: "Front-month volatility widens; stress scenario probabilities may increase for Oil&Gas exposures.",
    type: "market",
    severity: "high",
    sentiment: -0.22,
    reach: 0,
    timestamp: isoMinutesAgo(8),
    source: "bloomberg",
    country: "US",
    region: "North America",
    sector: "Oil & Gas",
    riskFactor: "Market",
  },
  {
    id: "s-004",
    title: "APAC logistics lane rates reverse; margin pressure expected",
    body: "Freight indexes down 11% MoM; review downside for Industrials logistics JV assumptions.",
    type: "risk",
    severity: "high",
    sentiment: -0.33,
    reach: 0,
    timestamp: isoMinutesAgo(66),
    source: "internal",
    country: "SG",
    region: "APAC",
    sector: "Logistics",
    riskFactor: "Operational",
  },
  {
    id: "s-005",
    title: "Hospital staffing shortages intensify in key metro areas",
    body: "Wage inflation pressure persists; monitor operational risk on Hospitals roll-up integration.",
    type: "risk",
    severity: "high",
    sentiment: -0.41,
    reach: 120_000,
    timestamp: isoMinutesAgo(105),
    source: "talkwalker",
    country: "US",
    region: "North America",
    sector: "Hospitals",
    riskFactor: "Operational",
  },
  {
    id: "s-006",
    title: "EU taxonomy alignment update: solar assets gain clarity",
    body: "Updated guidance improves reporting certainty; positive read-through for Solar acquisitions pipeline.",
    type: "opportunity",
    severity: "high",
    sentiment: 0.44,
    reach: 0,
    timestamp: isoMinutesAgo(150),
    source: "bloomberg",
    country: "ES",
    region: "Europe",
    sector: "Solar & Energy",
  },
  {
    id: "s-007",
    title: "Liquidity thin in infra secondaries; bid/ask widens",
    body: "Deal execution windows shorten; ensure liquidity scoring reflects current market depth.",
    type: "market",
    severity: "high",
    sentiment: -0.18,
    reach: 0,
    timestamp: isoMinutesAgo(210),
    source: "internal",
    country: "GB",
    region: "Europe",
    sector: "Water Treatment",
    riskFactor: "Liquidity",
  },

  // medium ×8
  {
    id: "s-008",
    title: "Solar module prices stabilize after Q1 decline",
    body: "Input cost pressure eases; base case build costs likely hold for EU PV pipeline.",
    type: "market",
    severity: "medium",
    sentiment: 0.22,
    reach: 0,
    timestamp: isoMinutesAgo(24),
    source: "bloomberg",
    country: "ES",
    region: "Europe",
    sector: "Solar & Energy",
  },
  {
    id: "s-009",
    title: "Regional bank deposit betas remain elevated",
    body: "Funding costs drift higher; revisit sensitivity for Banking credit sleeve.",
    type: "risk",
    severity: "medium",
    sentiment: -0.28,
    reach: 0,
    timestamp: isoMinutesAgo(52),
    source: "internal",
    country: "US",
    region: "North America",
    sector: "Banking",
    riskFactor: "Credit",
  },
  {
    id: "s-010",
    title: "FX swing increases hedging costs in LatAm",
    body: "Forward points widen; scenario stress may reduce IRR for LatAm allocations.",
    type: "market",
    severity: "medium",
    sentiment: -0.19,
    reach: 0,
    timestamp: isoMinutesAgo(77),
    source: "bloomberg",
    country: "BR",
    region: "Latin America",
    sector: "Banking",
    riskFactor: "Market",
  },
  {
    id: "s-011",
    title: "Deal chatter: clinic network bolt-on under exclusivity",
    body: "Potential bolt-on adds scale; review integration capacity and staffing plan.",
    type: "deal",
    severity: "medium",
    sentiment: 0.16,
    reach: 58_000,
    timestamp: isoMinutesAgo(95),
    source: "talkwalker",
    country: "US",
    region: "North America",
    sector: "Hospitals",
    workflowItemId: "r-010",
  },
  {
    id: "s-012",
    title: "Kenya inflation print surprises to upside",
    body: "Input costs rise; review stress test for Agriculture platform unit economics.",
    type: "risk",
    severity: "medium",
    sentiment: -0.36,
    reach: 0,
    timestamp: isoMinutesAgo(133),
    source: "bloomberg",
    country: "KE",
    region: "Africa",
    sector: "Agriculture",
    riskFactor: "Market",
  },
  {
    id: "s-013",
    title: "EU bank M&A approvals accelerate",
    body: "Signals slightly improve for spread capture basket; monitor regulatory timelines.",
    type: "opportunity",
    severity: "medium",
    sentiment: 0.27,
    reach: 0,
    timestamp: isoMinutesAgo(170),
    source: "internal",
    country: "DE",
    region: "Europe",
    sector: "Banking",
    riskFactor: "Regulatory",
  },
  {
    id: "s-014",
    title: "Talkwalker: safety sentiment dips for North Sea services",
    body: "HSE discussion volume increases; confirm incident disclosures and mitigation plans.",
    type: "risk",
    severity: "medium",
    sentiment: -0.24,
    reach: 96_000,
    timestamp: isoMinutesAgo(195),
    source: "talkwalker",
    country: "GB",
    region: "Europe",
    sector: "Oil & Gas",
    riskFactor: "Operational",
  },
  {
    id: "s-015",
    title: "Policy draft: water tariff pass-through under review",
    body: "Potential amendment could limit FX pass-through; model sensitivity for Water PPP.",
    type: "policy",
    severity: "medium",
    sentiment: -0.21,
    reach: 0,
    timestamp: isoMinutesAgo(255),
    source: "internal",
    country: "CL",
    region: "Latin America",
    sector: "Water Treatment",
    riskFactor: "Regulatory",
  },

  // low ×12
  {
    id: "s-016",
    title: "Solar offtake pricing remains stable in Iberia",
    body: "No material changes in PPA curves this week.",
    type: "market",
    severity: "low",
    sentiment: 0.08,
    reach: 0,
    timestamp: isoMinutesAgo(14),
    source: "internal",
    country: "ES",
    region: "Europe",
    sector: "Solar & Energy",
  },
  {
    id: "s-017",
    title: "ESG note: improved disclosure cadence for utilities peers",
    body: "More frequent reporting supports governance scoring stability.",
    type: "policy",
    severity: "low",
    sentiment: 0.12,
    reach: 0,
    timestamp: isoMinutesAgo(31),
    source: "internal",
    country: "ES",
    region: "Europe",
    sector: "Solar & Energy",
  },
  {
    id: "s-018",
    title: "Banking: short-end rates drift lower",
    body: "Funding pressure modestly eases; recheck base case net interest margins.",
    type: "market",
    severity: "low",
    sentiment: 0.11,
    reach: 0,
    timestamp: isoMinutesAgo(58),
    source: "bloomberg",
    country: "US",
    region: "North America",
    sector: "Banking",
  },
  {
    id: "s-019",
    title: "Clinics: payer mix improves marginally",
    body: "Public data suggests improved reimbursement mix in select counties.",
    type: "opportunity",
    severity: "low",
    sentiment: 0.18,
    reach: 34_000,
    timestamp: isoMinutesAgo(82),
    source: "talkwalker",
    country: "US",
    region: "North America",
    sector: "Hospitals",
  },
  {
    id: "s-020",
    title: "LatAm banking: local liquidity conditions stable",
    body: "Money market spreads unchanged on the week.",
    type: "market",
    severity: "low",
    sentiment: 0.05,
    reach: 0,
    timestamp: isoMinutesAgo(112),
    source: "bloomberg",
    country: "BR",
    region: "Latin America",
    sector: "Banking",
  },
  {
    id: "s-021",
    title: "Deal pipeline: two PV portfolios approach market",
    body: "Potential competitive process; consider pre-emptive diligence allocation.",
    type: "deal",
    severity: "low",
    sentiment: 0.21,
    reach: 0,
    timestamp: isoMinutesAgo(145),
    source: "internal",
    country: "ES",
    region: "Europe",
    sector: "Solar & Energy",
  },
  {
    id: "s-022",
    title: "Materials: copper forward curve flattens",
    body: "Price expectations soften slightly; keep commodity beta watchlist updated.",
    type: "market",
    severity: "low",
    sentiment: -0.06,
    reach: 0,
    timestamp: isoMinutesAgo(168),
    source: "bloomberg",
    country: "CL",
    region: "Latin America",
    sector: "Hotels",
  },
  {
    id: "s-023",
    title: "Africa: FX volatility steadies after prior spike",
    body: "Short-term stabilization; monitor for renewed stress signals.",
    type: "market",
    severity: "low",
    sentiment: 0.04,
    reach: 0,
    timestamp: isoMinutesAgo(188),
    source: "internal",
    country: "KE",
    region: "Africa",
    sector: "Agriculture",
  },
  {
    id: "s-024",
    title: "Policy: healthcare reimbursement commentary neutral",
    body: "No material changes indicated in committee updates.",
    type: "policy",
    severity: "low",
    sentiment: 0.02,
    reach: 0,
    timestamp: isoMinutesAgo(232),
    source: "internal",
    country: "FR",
    region: "Europe",
    sector: "Hospitals",
  },
  {
    id: "s-025",
    title: "Opportunity: tax credit transfer market deepens in US",
    body: "Improved liquidity for tax credit transfers; positive for Solar projects.",
    type: "opportunity",
    severity: "low",
    sentiment: 0.26,
    reach: 0,
    timestamp: isoMinutesAgo(275),
    source: "bloomberg",
    country: "US",
    region: "North America",
    sector: "Solar & Energy",
  },
  {
    id: "s-026",
    title: "Deal: bank capital notes issuance window opens",
    body: "Issuer calendars indicate favorable near-term issuance for EU notes.",
    type: "deal",
    severity: "low",
    sentiment: 0.10,
    reach: 0,
    timestamp: isoMinutesAgo(305),
    source: "bloomberg",
    country: "DE",
    region: "Europe",
    sector: "Banking",
  },
  {
    id: "s-027",
    title: "Risk: minor operational disruption reported at logistics hub",
    body: "Short-lived disruption; track if incident frequency increases.",
    type: "risk",
    severity: "low",
    sentiment: -0.10,
    reach: 22_000,
    timestamp: isoMinutesAgo(340),
    source: "talkwalker",
    country: "SG",
    region: "APAC",
    sector: "Logistics",
    riskFactor: "Operational",
  },
];
